### ISSUE TITLE
First merged spreadsheet for review

### ISSUE THREAD

**Issue by zonca** [oirlab/iris_icd_tool#2]
@arunsurya77 @ikashell 

I created a spreadsheet that merges both:

* telemetry that is in the ICD (and I will write a small script to generate the ICD `subscribe-model.conf` https://github.com/tmt-icd/IRIS-Model-Files/blob/master/drs/drs-assembly/subscribe-model.conf), I created another column `isEvent` which is 1 if this row should go into the ICD, there are some ICD events which are received by IRIS but don't go into any FITS header
* FITS keywords in the file, some keywords come from telemetry and are also in the ICD, others are not.

see:
https://docs.google.com/spreadsheets/d/1D-e615yT1MA8fyRQeD7jPNMoNALHDM8_dgA1VQUbqO0/edit?usp=sharing

You can either leave comments on Google or reply here.

I also noticed that the `RequiredRate` column is mostly empty

**Comment by arunsurya77** [comment]
@zonca Why is some of the entries in the new sheet have missing origin substem and component for some entries. I mean for entries for which the original sheet had both. Should I just edit the new sheet ?

**Comment by zonca** [comment]
no, please leave a comment in the doc to point me to those rows, so I can rerun the automated script and fix all of them.

**Comment by zonca** [comment]
@arunsurya77 can you please comment on the sheet over the missing rows? thanks

**Comment by arunsurya77** [comment]
Hi Andrea ,
I think one of the reasons there were few missing event names for keywords
was that in the master sheet I only put (assembly, subsystem, event) for
the first variable in that structure. For later variables of that
subscription, the (assembly, subsystem, event) was blank. I have corrected
this now in the sheet. Now all metadata with subscriptions has
their (assembly, subsystem, event) filled out. Can you try running the code
again?


master Sheet:
(
https://docs.google.com/spreadsheets/d/1BZ7tCI6w8wkjrauZqGwZbrWzp1S_D6Nfi8AR2NSwiM0/edit?usp=sharing
)

Cheers
Arun

**Comment by zonca** [comment]
very good, thanks @arunsurya77 I merged them in.

I think that from now on we can consider https://docs.google.com/spreadsheets/d/1D-e615yT1MA8fyRQeD7jPNMoNALHDM8_dgA1VQUbqO0/edit?usp=sharing to be the new master sheet,

I also created a new repository with some documentation related to this

https://github.com/oirlab/iris_metadata
